#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "Este script deve ser execuado como root." 
   exit 1
fi

if [[ "$(mount | grep '/dev/sda2 on / type btrfs')" == *"subvol=/ROOT)"* ]];then 
    if [ -n "$(yadm -Y /etc/yadm diff --name-only)" ]; then
        yadm -Y /etc/yadm diff
        if [ $(yadm -Y /etc/yadm diff --name-only | wc -l) -ge 2 ]; then
            echo -e "\nARQUIVOS MODIFICADOS:"
            for i in $(yadm -Y /etc/yadm diff --name-only); do
                echo -e "/$i";
            done
        else
            echo -e "\nARQUIVO MODIFICADO:\n/$(yadm -Y /etc/yadm diff --name-only)\n"
        fi
    fi
    if [ $(yadm -Y /etc/yadm status --porcelain | grep "^A" | cut -c 4- | wc -l) -ge 2 ]; then
        echo -e "\nARQUIVOS ADICIONADOS:"
        for i in $(yadm -Y /etc/yadm status --porcelain | grep "^A" | cut -c 4-); do
            echo -e "/$i";
        done
    elif [ $(yadm -Y /etc/yadm status --porcelain | grep "^A" | cut -c 4- | wc -l) -eq 1 ]; then
        echo -e "\nARQUIVO ADICIONADO:\n/$(yadm -Y /etc/yadm status --porcelain | grep "^A" | cut -c 4-)\n"
    fi
    yadm -Y /etc/yadm commit -a -m "atualizando"
else
    echo -e "Você não está no subvolume ROOT. push não realizado"
fi
